Homework 9
MaksKulykov/FilmCatalog pull request #2
Opened 2017-05-22 06:54 UTC by MaksKulykov

2017-05-31 18:20 UTC, ghost requested changes
мелкие изменения

2017-05-31 18:20 UTC, captainkovalsky commented on src/app/film-card/film-card.component.ts
> +  filmItem: Object[] = [];
@MaksKulykov Имя filmItem имеет тип массив, выберите более подходящее имя + плюс не используйте Object[] можно просто any[]

2017-06-01 08:39 UTC, MaksKulykov commented on src/app/film-card/film-card.component.ts
> +  filmItem: Object[] = [];
@captainkovalsky 
done

2017-06-02 10:45 UTC, ghost approved these changes

2017-06-02 12:07 UTC, merged