Homework 10
MaksKulykov/FilmCatalog pull request #3
Opened 2017-05-30 16:34 UTC by MaksKulykov

2017-05-31 18:13 UTC, ghost requested changes
Прописал коменты

2017-05-31 18:13 UTC, captainkovalsky commented on src/app/film-list/film-list.component.html
> +<app-search (getFilms)="validateFilmName($event)" (selectView)="selectView($event)"></app-search>
Перейменовать метод в более удобное имя

2017-05-31 18:13 UTC, captainkovalsky commented on src/app/film-list/film-list.component.ts
> +    if (this.filmName === filmName) {
Один метод и подгружает новые данные и ищет
Разделить на два отдельных и использовать по отдельности

2017-06-01 08:36 UTC, MaksKulykov commented on src/app/film-list/film-list.component.ts
> +    if (this.filmName === filmName) {
@captainkovalsky 
created select-view component

2017-06-02 10:44 UTC, ghost approved these changes

2017-06-02 12:13 UTC, merged