Homework 11
MaksKulykov/FilmCatalog pull request #4
Opened 2017-06-09 10:55 UTC by MaksKulykov

2017-06-13 19:58 UTC, ghost requested changes
Мелкие изменения

2017-06-13 19:58 UTC, captainkovalsky commented on src/app/app.component.ts
> +  constructor(private renderer: Renderer) {
@MaksKulykov логика по скроллингу никак не связаная с листами соостветсвенно в компоненте   она наршует принцип единой ответсвенности. Плюс еще логику по кнопке листание наверх трудно переиспользовать. В таком случае рекомендую ее вынести в отдельную директиву.
Вот рабочая директива https://gist.github.com/captainkovalsky/0c4da02038f881695ed7330e718883bb

Пример как ее можно на кнопке использовать https://gist.github.com/captainkovalsky/0c56efbeb8b3a7f4d32b4fc818ee366b

P.S. Renderer устарел если такой вариант был бы ок то нужно было б использовать Renderer2

2017-06-13 19:58 UTC, captainkovalsky commented on src/app/app.component.ts
> +    this.renderer.listenGlobal('window', 'scroll', (event) => {this.scrollFunction();} );
@MaksKulykov В коменте выше можете посмотреть как сделать красиво

2017-06-13 20:00 UTC, captainkovalsky commented on src/app/app.component.ts
> +    this.renderer.listenGlobal('window', 'scroll', (event) => {this.scrollFunction();} );
Наиболее лучший вариант это сделать отдельную компоненту GoTop для кнопки и у нее переиспользовать директиву showWhenScroll

2017-06-14 09:37 UTC, MaksKulykov commented on src/app/app.component.ts
> +  constructor(private renderer: Renderer) {
@captainkovalsky done

2017-06-14 09:37 UTC, MaksKulykov commented on src/app/app.component.ts
> +    this.renderer.listenGlobal('window', 'scroll', (event) => {this.scrollFunction();} );
@captainkovalsky done

2017-06-21 07:17 UTC, ghost approved these changes

2017-06-21 18:54 UTC, merged